export const GET_GITHUB_USERS_BY_SINCE = "GET_GITHUB_USERS_BY_SINCE";
export const GET_GITHUB_USER_DETAILS = "GET_GITHUB_USER_DETAILS";
export const GET_GITHUB_USER_REPOS = "GET_GITHUB_USER_REPOS";
export const SET_PAGINATION = "SET_PAGINATION";
