export const GET_GITHUB_USERS = "GET_GITHUB_USERS";
export const GET_GITHUB_USER_DETAILS = "GET_GITHUB_USER_DETAILS";
export const GET_GITHUB_USER_REPOS = "GET_GITHUB_USER_REPOS";
export const SET_PAGINATION = "SET_PAGINATION";
